### ISSUE TITLE
PlaceholderAPIEvent may only be triggered synchronously.

### ISSUE THREAD

**Issue by Patbox** [APickledWalrus/skript-placeholders#4]
### Description

I'm trying to use Skript-made placeholders with TitleManager,but they don't work.
### Steps to Reproduce

Add skript placeholder to TitleManager scoreboard. Done!
### Expected Behavior

I get placeholder on a ScoreBoard
### Errors / Screenshots

`[16:12:00 WARN]: java.lang.IllegalStateException: PlaceholderAPIEvent may only be triggered synchronously.
[16:12:00 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533)
[16:12:00 WARN]: 	at io.github.apickledwalrus.placeholderaddon.placeholderapi.PlaceholderAPIListener.onPlaceholderRequest(PlaceholderAPIListener.java:36)
[16:12:00 WARN]: 	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
[16:12:00 WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234)
[16:12:00 WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:374)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.placeholder.PlaceholderAPIHook.replacePlaceholders(Hooks.kt:17)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.APIProvider.replaceText(APIProvider.kt:158)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.APIProvider.setScoreboardValueWithPlaceholders(APIProvider.kt:605)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.TitleManagerPlugin.setScoreboardValueWithPlaceholders(TitleManagerPlugin.kt)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setScoreboardValue(PlayerExtensions.kt:169)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.APIProvider$toScoreboardValueAnimation$4.invoke(APIProvider.kt:358)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.APIProvider$toScoreboardValueAnimation$4.invoke(APIProvider.kt:46)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:81)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation$update$2.invoke(PartBasedSendableAnimation.kt:88)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation$update$2.invoke(PartBasedSendableAnimation.kt:11)
[16:12:00 WARN]: 	at io.puharesource.mc.titlemanager.scheduling.AsyncScheduler$scheduleRaw$1.run(AsyncScheduler.kt:43)
[16:12:00 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:12:00 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:12:00 WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[16:12:00 WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[16:12:00 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:12:00 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:12:00 WARN]: 	at java.lang.Thread.run(Thread.java:748)
`

### Server Information
* **Server version/platform:** Paper 1.14.4 (230)        
* **skript-placeholders version:** 1.3               
* **Skript version:** 2.4               
* **PlaceholderAPI version:** 2.10.4                
* *TitleManager version*: 2.1.5

### Additional Context

 TitleManager plugin: https://www.spigotmc.org/resources/titlemanager.1049/

**Comment by APickledWalrus** [comment]
Fixed in the next release :)
