### ISSUE TITLE
skript with placeholders erreur in Paper 1.20.1

### ISSUE THREAD

**Issue by Jeremylo1** [APickledWalrus/skript-placeholders#40]
### Description
Since upgrading from Paper 1.19.4 to Paper 1.20.1, I'm experiencing a problem with the "skript-placeholder" plugin. When loading my skript using placeholders, I get the following errors

### Steps to Reproduce
1- Installer Skript 2.6.4 or 2.7.0
2- Install skript-placeholder
3- Place this skript in scripts (Points.sk) file

```
on placeholderapi placeholder request for the prefix "skriptjoueur":
	if the identifier is "point": # The placeholder would be 'skriptjoueur_point'
		if {PointsJoueur.%player's uuid%} is not set:
			set {PointsJoueur.%player's uuid%} to 0
		set the result to "%{PointsJoueur.%player's uuid%}%"
```
4- Tape "/sk reload Points.sk"

### Expected Behavior
When I use "/papi parse me %skriptjoueur_point%" I should get 0 but instead I get the message "%skriptjoueur_point%".

### Errors / Screenshots
```
[06:09:26 ERROR]: #!#! 
[06:09:26 ERROR]: #!#! [Skript] Severe Error:
[06:09:26 ERROR]: #!#! Could not load Points.sk
[06:09:26 ERROR]: #!#! 
[06:09:26 ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[06:09:26 ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[06:09:26 ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[06:09:26 ERROR]: #!#! 
[06:09:26 ERROR]: #!#! Stack trace:
[06:09:26 ERROR]: #!#! java.lang.IllegalStateException: ExpansionRegisterEvent may only be triggered synchronously.
[06:09:26 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)
[06:09:26 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[06:09:26 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[06:09:26 ERROR]: #!#!     at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:273)
[06:09:26 ERROR]: #!#!     at PlaceholderAPI-2.11.3.jar//me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:139)
[06:09:26 ERROR]: #!#!     at skript-placeholders-1.5.2.jar//io.github.apickledwalrus.skriptplaceholders.skript.elements.events.EvtPlaceholderRequest.init(EvtPlaceholderRequest.java:104)
[06:09:26 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1054)
[06:09:26 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1020)
[06:09:26 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:740)
[06:09:26 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[06:09:26 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[06:09:26 ERROR]: #!#!     at Skript-2.6.4.jar//ch.njol.skript.ScriptLoader$AsyncLoaderThread.run(ScriptLoader.java:368)
[06:09:26 ERROR]: #!#! 
[06:09:26 ERROR]: #!#! Version Information:
[06:09:26 ERROR]: #!#!   Skript: 2.6.4 (OUTDATED)
[06:09:26 ERROR]: #!#!     Flavor: skriptlang-github
[06:09:26 ERROR]: #!#!     Date: 17:14:25.041218900
[06:09:26 ERROR]: #!#!   Bukkit: 1.20.1-R0.1-SNAPSHOT
[06:09:26 ERROR]: #!#!   Minecraft: 1.20.1
[06:09:26 ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[06:09:26 ERROR]: #!#!   OS: Linux amd64 5.10.0-18-amd64
[06:09:26 ERROR]: #!#! 
[06:09:26 ERROR]: #!#! Server platform: Paper
[06:09:26 ERROR]: #!#! 
[06:09:26 ERROR]: #!#! Current node: on placeholderapi placeholder request for the prefix "skriptjoueur": (Points.sk, line 120)
[06:09:26 ERROR]: #!#! Current item: null
[06:09:26 ERROR]: #!#! 
[06:09:26 ERROR]: #!#! Thread: Thread-10
[06:09:26 ERROR]: #!#! 
[06:09:26 ERROR]: #!#! Language: english
[06:09:26 ERROR]: #!#! Link parse mode: DISABLED
[06:09:26 ERROR]: #!#! 
[06:09:26 ERROR]: #!#! End of Error.
[06:09:26 ERROR]: #!#! 
```

### Server Information
* **Server version/platform:**       git-Paper-60 (MC: 1.20.1)
* **skript-placeholders version:**                1.5.2
* **Skript version:**                2.6.4 and 2.7.0
* **PlaceholderAPI version:**                 2.11.3

Thanks in advance :)

**Comment by APickledWalrus** [comment]
What is your value for `script loader thread size` in config.sk? See: https://github.com/SkriptLang/Skript/blob/011c91eb06c0fb8d5bfc0df385ee3d5dc9a0ef9c/src/main/resources/config.sk#L181

**Comment by Jeremylo1** [comment]
script loader thread size: 2

**Comment by APickledWalrus** [comment]
That would likely be why you're having issues. It's something I need to account for here. For the moment, however, you can change that value to 0 and the addon should work correctly.

**Comment by Jeremylo1** [comment]
Indeed, it seems to solve the problem! Thanks for your quick help! I hope you'll be able to fix this thread problem in the future.

**Comment by APickledWalrus** [comment]
Will be fixed in the next release :)
