### ISSUE TITLE
[BUG] Cannot return player‘s forge status while working with ClientDetector

### ISSUE THREAD

**Issue by fr1g** [APickledWalrus/skript-placeholders#49]
### Description
Skript reported errors that caused by ClientDetector just because a method returns null. Since this addon is the one which should process any kind of returns including "null".

### Steps to Reproduce
install CD and try to get placeholder "clientdetector_forge_user" in sk.

### Expected Behavior
It should get null and return the value as string "<null>" back to sk.

### Errors / Screenshots
```txt
 Stack trace:
[20:21:47] [Server thread/ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "de.sportkanone123.clientdetector.spigot.forgemod.ModList.getMods()" because the return value of "java.util.HashMap.get(Object)" is null
[20:21:47] [Server thread/ERROR]: #!#!     at de.sportkanone123.clientdetector.spigot.manager.PlaceholderManager.onPlaceholderRequest(PlaceholderManager.java:61)
[20:21:47] [Server thread/ERROR]: #!#!     at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
[20:21:47] [Server thread/ERROR]: #!#!     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326)
[20:21:47] [Server thread/ERROR]: #!#!     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:288)
[20:21:47] [Server thread/ERROR]: #!#!     at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:261)
[20:21:47] [Server thread/ERROR]: #!#!     at io.github.apickledwalrus.skriptplaceholders.skript.util.PlaceholderUtils.getPlaceholder(PlaceholderUtils.java:31)
[20:21:47] [Server thread/ERROR]: #!#!     at io.github.apickledwalrus.skriptplaceholders.skript.elements.expressions.ExprParsePlaceholder.get(ExprParsePlaceholder.java:70)
[20:21:47] [Server thread/ERROR]: #!#!     at io.github.apickledwalrus.skriptplaceholders.skript.elements.expressions.ExprParsePlaceholder.get(ExprParsePlaceholder.java:23)
[20:21:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
[20:21:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:272)
```

### Server Information
* **Server version/platform:**       Spigot 1.20.1
* **skript-placeholders version:**                1.5.2
* **Skript version:**                2.7.0
* **PlaceholderAPI version (if applicable):**                2.10.6
* **MVdWPlaceholderAPI version (if applicable):**                none

**Comment by APickledWalrus** [comment]
This is not really something for me to handle. The issue is coming from within the plugin itself, so it's up to them to fix it.

**Comment by fr1g** [comment]
If you think parsing a null is not your business, then I will push the issue to CD’s repo.
I commit this issue to your place just because this stack trace printed by Skript…    :P

**Comment by APickledWalrus** [comment]
The stacktracke includes this plugin (as it is the one trying to obtain the value), but it is ClientDetector itself that is ultimately the cause.
